version: '3.4'

services:
  microservicio1:
    image: ${DOCKER_REGISTRY-}microservicio1
    build:
      context: .
      dockerfile: Microservicio1/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
  microservicio2:
    image: ${DOCKER_REGISTRY-}microservicio2
    build:
      context: .
      dockerfile: Microservicio2/Dockerfile
    ports:
    - "5002:5002"
    - "5003:5003"
